### PR TITLE
Issues #67: Implemented the possibility to customize the html redirection of the page. 

### PR DESCRIPTION
**Pull request by jonathandsantiago**
Created the RedirectHtmlType that defines what will be presented in the redirect's HTML.
`enum RedirectHtmlType { htmlDefault, loading, custom }`
By default is `htmlDefault`
And the `loading` type, which
image

And there's `custom`, so that everyone can customize it the way they want.
I made a PR so I can get into the version.
Would you like to see the possibility of approval for us in this evolution?
Issues #67

### CODE REVIEW

**Comment by inf0rmatix** [comment]
hey @rbellens I could really use this PR :)

**Comment by buehler** [comment]
@inf0rmatix I guess this repository is not maintained anymore.
the same PR is open over at #59.

As soon as I find the time, I'll fork this and implement the thing.

**Comment by buehler** [comment]
A question @jonathandsantiago: is this allowed in a mobile app?
I thought the in-app browser mechanism must be used to use auth inside android/ios. for mac/windows/linux, one should use the normal browser. for native apps: `flutter_appauth`

**Comment by jonathandsantiago** [comment]
Hello @buehler, as no one responded, we forked the project and created the [oauth_client](https://pub.dev/packages/oauth_client). Here we made some customizations and fixes

**Comment by rbellens** [comment]
@jonathandsantiago Thanks for this PR!
This PR becomes obsolete after merging of PR #66. PR #66 does not have predefined htmls, only allows custom html. So, you'll need to use to define the html in your own code, or we could think of a new PR with some static defined html.

**Pull request closed without merging**
