### PR TITLE
upgrade http dependency. Fixes #92

### LINKED ISSUE #92: Update http dependency to 1.0.0?
Hello! 
It would be awesome if you could update the http dependency to http: ^1.1.0 in pubspec.yaml
This will allow us to compile your library with the newest http dependencies.

### PR DESCRIPTION
**Pull request by wstrange**
Fixes #92

### CODE REVIEW

**Comment by bvoq** [comment]
Please merge this one, so we can use http: 1.0.0 .

**Comment by walsha2** [comment]
@wstrange it might be better to leave the http requirements a little more relaxed. Lots of packages use `http` and have yet to update. 

The `http` usage here is very light and the new changes to `http` package are all backwards compatible for the needs of this `openid_client`

See #96 where I also proposed this change:

```
http: ">=0.13.5 <2.0.0"
```

**Comment by wstrange** [comment]
@rbellens Rick - any chance you can push this PR to pub.dev? This should be a low risk change.

**Comment by walsha2** [comment]
> @rbellens Rick - any chance you can push this PR to pub.dev? This should be a low risk change. 
> 
> 

@rbellens ditto with #96 🙏

**Comment by toonvanstrijp** [comment]
Can this gets merged and released? It's kind of an blocking issue right now :) thank you for taking the time, I know it's not easy to maintain a library.

**Comment by mrzanirato** [comment]
Please, can you merge? Thanks @rbellens

**Comment by rbellens** [comment]
sorry for the delay. This is now fixed and released

**Pull request merged**
