### PR TITLE
redirectHtml parameter is added to Authenticator

### PR DESCRIPTION
**Pull request by drzoshi**
redirectHtml parameter is added to Authenticator so that consumer can pass their own response html for localhost redirectUrl

Issue Url: https://github.com/appsup-dart/openid_client/issues/27

### CODE REVIEW

**Comment by buehler** [comment]
I just wanted to start implementing this. This would improve the user experience by a thousandfold!

**Comment by buehler** [comment]
@rbellens any chance we could get this merged?

**Comment by buehler** [comment]
Anyone? @rbellens @passsy @ABausG 
I would rather not fork the repo to use a fixed dart git dependency. This would be a real nice addition without much effort to review it :-)

**Review by buehler — APPROVED** [review]

**Comment by rbellens** [comment]
@drzoshi Thanks for this PR!
This PR is now obsolete after merging PR #66.

**Pull request closed without merging**
